name: Windows Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  # TODO: https://github.com/otiai10/gosseract/issues/262
  # push:
  #   branches: [main, develop, windows/*]
  # pull_request:
  #   branches: [main, develop]
  push:
    branches: [windows/*]

jobs:
  windows-test:
    runs-on: windows-latest
    name: Windows Test
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
    # - name: Setup Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.18
    # - name: Search packages
    #   run: |
    #     vcpkg search tesseract
    #     vcpkg search leptonica
    - name: Debug_1
      run: |
        Get-ChildItem Env:
    - name: Debug_2
      run: |
        $Env:INCLUDE += ';C:\vcpkg\installed\x64-windows\include'
    - name: Debug_F
      run: |
        Get-ChildItem Env:

    # - name: Install Tesseract
    #   run: |
    #     vcpkg install tesseract:x64-windows --head
    # - name: Check installation
    #   run: |
    #     dir C:\vcpkg\installed\x64-windows\include
    #     dir C:\vcpkg\installed\x64-windows\lib
    # - name: Test Gosseract
    #   run: |
    #     SET INCLUDE="%INCLUDE%;C:\vcpkg\installed\x64-windows\include"
    #     go test -v -cover ./...
